export type Country = { iso2: string; name: string; dialCode: string };

// ISO 3166-1 alpha-2 + E.164 calling code, names in Spanish.
export const COUNTRIES: Country[] = [
  { iso2: "AF", name: "Afganistán", dialCode: "93" },
  { iso2: "AL", name: "Albania", dialCode: "355" },
  { iso2: "DE", name: "Alemania", dialCode: "49" },
  { iso2: "AD", name: "Andorra", dialCode: "376" },
  { iso2: "AO", name: "Angola", dialCode: "244" },
  { iso2: "AI", name: "Anguila", dialCode: "1264" },
  { iso2: "AG", name: "Antigua y Barbuda", dialCode: "1268" },
  { iso2: "SA", name: "Arabia Saudita", dialCode: "966" },
  { iso2: "DZ", name: "Argelia", dialCode: "213" },
  { iso2: "AR", name: "Argentina", dialCode: "54" },
  { iso2: "AM", name: "Armenia", dialCode: "374" },
  { iso2: "AW", name: "Aruba", dialCode: "297" },
  { iso2: "AU", name: "Australia", dialCode: "61" },
  { iso2: "AT", name: "Austria", dialCode: "43" },
  { iso2: "AZ", name: "Azerbaiyán", dialCode: "994" },
  { iso2: "BS", name: "Bahamas", dialCode: "1242" },
  { iso2: "BH", name: "Baréin", dialCode: "973" },
  { iso2: "BD", name: "Bangladés", dialCode: "880" },
  { iso2: "BB", name: "Barbados", dialCode: "1246" },
  { iso2: "BE", name: "Bélgica", dialCode: "32" },
  { iso2: "BZ", name: "Belice", dialCode: "501" },
  { iso2: "BJ", name: "Benín", dialCode: "229" },
  { iso2: "BM", name: "Bermudas", dialCode: "1441" },
  { iso2: "BY", name: "Bielorrusia", dialCode: "375" },
  { iso2: "BO", name: "Bolivia", dialCode: "591" },
  { iso2: "BA", name: "Bosnia y Herzegovina", dialCode: "387" },
  { iso2: "BW", name: "Botsuana", dialCode: "267" },
  { iso2: "BR", name: "Brasil", dialCode: "55" },
  { iso2: "BN", name: "Brunéi", dialCode: "673" },
  { iso2: "BG", name: "Bulgaria", dialCode: "359" },
  { iso2: "BF", name: "Burkina Faso", dialCode: "226" },
  { iso2: "BI", name: "Burundi", dialCode: "257" },
  { iso2: "BT", name: "Bután", dialCode: "975" },
  { iso2: "CV", name: "Cabo Verde", dialCode: "238" },
  { iso2: "KH", name: "Camboya", dialCode: "855" },
  { iso2: "CM", name: "Camerún", dialCode: "237" },
  { iso2: "CA", name: "Canadá", dialCode: "1" },
  { iso2: "QA", name: "Catar", dialCode: "974" },
  { iso2: "KZ", name: "Kazajistán", dialCode: "7" },
  { iso2: "TD", name: "Chad", dialCode: "235" },
  { iso2: "CL", name: "Chile", dialCode: "56" },
  { iso2: "CN", name: "China", dialCode: "86" },
  { iso2: "CY", name: "Chipre", dialCode: "357" },
  { iso2: "VA", name: "Ciudad del Vaticano", dialCode: "379" },
  { iso2: "CO", name: "Colombia", dialCode: "57" },
  { iso2: "KM", name: "Comoras", dialCode: "269" },
  { iso2: "KP", name: "Corea del Norte", dialCode: "850" },
  { iso2: "KR", name: "Corea del Sur", dialCode: "82" },
  { iso2: "CI", name: "Costa de Marfil", dialCode: "225" },
  { iso2: "CR", name: "Costa Rica", dialCode: "506" },
  { iso2: "HR", name: "Croacia", dialCode: "385" },
  { iso2: "CU", name: "Cuba", dialCode: "53" },
  { iso2: "CW", name: "Curazao", dialCode: "599" },
  { iso2: "DK", name: "Dinamarca", dialCode: "45" },
  { iso2: "DM", name: "Dominica", dialCode: "1767" },
  { iso2: "EC", name: "Ecuador", dialCode: "593" },
  { iso2: "EG", name: "Egipto", dialCode: "20" },
  { iso2: "SV", name: "El Salvador", dialCode: "503" },
  { iso2: "AE", name: "Emiratos Árabes Unidos", dialCode: "971" },
  { iso2: "ER", name: "Eritrea", dialCode: "291" },
  { iso2: "SK", name: "Eslovaquia", dialCode: "421" },
  { iso2: "SI", name: "Eslovenia", dialCode: "386" },
  { iso2: "ES", name: "España", dialCode: "34" },
  { iso2: "US", name: "Estados Unidos", dialCode: "1" },
  { iso2: "EE", name: "Estonia", dialCode: "372" },
  { iso2: "SZ", name: "Esuatini", dialCode: "268" },
  { iso2: "ET", name: "Etiopía", dialCode: "251" },
  { iso2: "PH", name: "Filipinas", dialCode: "63" },
  { iso2: "FI", name: "Finlandia", dialCode: "358" },
  { iso2: "FJ", name: "Fiyi", dialCode: "679" },
  { iso2: "FR", name: "Francia", dialCode: "33" },
  { iso2: "GA", name: "Gabón", dialCode: "241" },
  { iso2: "GM", name: "Gambia", dialCode: "220" },
  { iso2: "GE", name: "Georgia", dialCode: "995" },
  { iso2: "GH", name: "Ghana", dialCode: "233" },
  { iso2: "GI", name: "Gibraltar", dialCode: "350" },
  { iso2: "GD", name: "Granada", dialCode: "1473" },
  { iso2: "GR", name: "Grecia", dialCode: "30" },
  { iso2: "GL", name: "Groenlandia", dialCode: "299" },
  { iso2: "GP", name: "Guadalupe", dialCode: "590" },
  { iso2: "GU", name: "Guam", dialCode: "1671" },
  { iso2: "GT", name: "Guatemala", dialCode: "502" },
  { iso2: "GF", name: "Guayana Francesa", dialCode: "594" },
  { iso2: "GY", name: "Guyana", dialCode: "592" },
  { iso2: "GN", name: "Guinea", dialCode: "224" },
  { iso2: "GQ", name: "Guinea Ecuatorial", dialCode: "240" },
  { iso2: "GW", name: "Guinea-Bisáu", dialCode: "245" },
  { iso2: "HT", name: "Haití", dialCode: "509" },
  { iso2: "HN", name: "Honduras", dialCode: "504" },
  { iso2: "HK", name: "Hong Kong", dialCode: "852" },
  { iso2: "HU", name: "Hungría", dialCode: "36" },
  { iso2: "IN", name: "India", dialCode: "91" },
  { iso2: "ID", name: "Indonesia", dialCode: "62" },
  { iso2: "IQ", name: "Irak", dialCode: "964" },
  { iso2: "IR", name: "Irán", dialCode: "98" },
  { iso2: "IE", name: "Irlanda", dialCode: "353" },
  { iso2: "IS", name: "Islandia", dialCode: "354" },
  { iso2: "KY", name: "Islas Caimán", dialCode: "1345" },
  { iso2: "CK", name: "Islas Cook", dialCode: "682" },
  { iso2: "FO", name: "Islas Feroe", dialCode: "298" },
  { iso2: "MH", name: "Islas Marshall", dialCode: "692" },
  { iso2: "SB", name: "Islas Salomón", dialCode: "677" },
  { iso2: "TC", name: "Islas Turcas y Caicos", dialCode: "1649" },
  { iso2: "VG", name: "Islas Vírgenes Británicas", dialCode: "1284" },
  { iso2: "VI", name: "Islas Vírgenes de EE. UU.", dialCode: "1340" },
  { iso2: "IL", name: "Israel", dialCode: "972" },
  { iso2: "IT", name: "Italia", dialCode: "39" },
  { iso2: "JM", name: "Jamaica", dialCode: "1876" },
  { iso2: "JP", name: "Japón", dialCode: "81" },
  { iso2: "JE", name: "Jersey", dialCode: "44" },
  { iso2: "JO", name: "Jordania", dialCode: "962" },
  { iso2: "KE", name: "Kenia", dialCode: "254" },
  { iso2: "KG", name: "Kirguistán", dialCode: "996" },
  { iso2: "KI", name: "Kiribati", dialCode: "686" },
  { iso2: "KW", name: "Kuwait", dialCode: "965" },
  { iso2: "LA", name: "Laos", dialCode: "856" },
  { iso2: "LS", name: "Lesoto", dialCode: "266" },
  { iso2: "LV", name: "Letonia", dialCode: "371" },
  { iso2: "LB", name: "Líbano", dialCode: "961" },
  { iso2: "LR", name: "Liberia", dialCode: "231" },
  { iso2: "LY", name: "Libia", dialCode: "218" },
  { iso2: "LI", name: "Liechtenstein", dialCode: "423" },
  { iso2: "LT", name: "Lituania", dialCode: "370" },
  { iso2: "LU", name: "Luxemburgo", dialCode: "352" },
  { iso2: "MO", name: "Macao", dialCode: "853" },
  { iso2: "MK", name: "Macedonia del Norte", dialCode: "389" },
  { iso2: "MG", name: "Madagascar", dialCode: "261" },
  { iso2: "MY", name: "Malasia", dialCode: "60" },
  { iso2: "MW", name: "Malaui", dialCode: "265" },
  { iso2: "MV", name: "Maldivas", dialCode: "960" },
  { iso2: "ML", name: "Malí", dialCode: "223" },
  { iso2: "MT", name: "Malta", dialCode: "356" },
  { iso2: "MA", name: "Marruecos", dialCode: "212" },
  { iso2: "MQ", name: "Martinica", dialCode: "596" },
  { iso2: "MU", name: "Mauricio", dialCode: "230" },
  { iso2: "MR", name: "Mauritania", dialCode: "222" },
  { iso2: "YT", name: "Mayotte", dialCode: "262" },
  { iso2: "MX", name: "México", dialCode: "52" },
  { iso2: "FM", name: "Micronesia", dialCode: "691" },
  { iso2: "MD", name: "Moldavia", dialCode: "373" },
  { iso2: "MC", name: "Mónaco", dialCode: "377" },
  { iso2: "MN", name: "Mongolia", dialCode: "976" },
  { iso2: "ME", name: "Montenegro", dialCode: "382" },
  { iso2: "MS", name: "Montserrat", dialCode: "1664" },
  { iso2: "MZ", name: "Mozambique", dialCode: "258" },
  { iso2: "MM", name: "Myanmar", dialCode: "95" },
  { iso2: "NA", name: "Namibia", dialCode: "264" },
  { iso2: "NR", name: "Nauru", dialCode: "674" },
  { iso2: "NP", name: "Nepal", dialCode: "977" },
  { iso2: "NI", name: "Nicaragua", dialCode: "505" },
  { iso2: "NE", name: "Níger", dialCode: "227" },
  { iso2: "NG", name: "Nigeria", dialCode: "234" },
  { iso2: "NU", name: "Niue", dialCode: "683" },
  { iso2: "NO", name: "Noruega", dialCode: "47" },
  { iso2: "NC", name: "Nueva Caledonia", dialCode: "687" },
  { iso2: "NZ", name: "Nueva Zelanda", dialCode: "64" },
  { iso2: "OM", name: "Omán", dialCode: "968" },
  { iso2: "NL", name: "Países Bajos", dialCode: "31" },
  { iso2: "PK", name: "Pakistán", dialCode: "92" },
  { iso2: "PW", name: "Palaos", dialCode: "680" },
  { iso2: "PS", name: "Palestina", dialCode: "970" },
  { iso2: "PA", name: "Panamá", dialCode: "507" },
  { iso2: "PG", name: "Papúa Nueva Guinea", dialCode: "675" },
  { iso2: "PY", name: "Paraguay", dialCode: "595" },
  { iso2: "PE", name: "Perú", dialCode: "51" },
  { iso2: "PF", name: "Polinesia Francesa", dialCode: "689" },
  { iso2: "PL", name: "Polonia", dialCode: "48" },
  { iso2: "PT", name: "Portugal", dialCode: "351" },
  { iso2: "PR", name: "Puerto Rico", dialCode: "1787" },
  { iso2: "GB", name: "Reino Unido", dialCode: "44" },
  { iso2: "CF", name: "República Centroafricana", dialCode: "236" },
  { iso2: "CZ", name: "República Checa", dialCode: "420" },
  { iso2: "CD", name: "República Democrática del Congo", dialCode: "243" },
  { iso2: "CG", name: "República del Congo", dialCode: "242" },
  { iso2: "DO", name: "República Dominicana", dialCode: "1809" },
  { iso2: "RE", name: "Reunión", dialCode: "262" },
  { iso2: "RW", name: "Ruanda", dialCode: "250" },
  { iso2: "RO", name: "Rumanía", dialCode: "40" },
  { iso2: "RU", name: "Rusia", dialCode: "7" },
  { iso2: "WS", name: "Samoa", dialCode: "685" },
  { iso2: "AS", name: "Samoa Americana", dialCode: "1684" },
  { iso2: "KN", name: "San Cristóbal y Nieves", dialCode: "1869" },
  { iso2: "SM", name: "San Marino", dialCode: "378" },
  { iso2: "PM", name: "San Pedro y Miquelón", dialCode: "508" },
  { iso2: "VC", name: "San Vicente y las Granadinas", dialCode: "1784" },
  { iso2: "LC", name: "Santa Lucía", dialCode: "1758" },
  { iso2: "ST", name: "Santo Tomé y Príncipe", dialCode: "239" },
  { iso2: "SN", name: "Senegal", dialCode: "221" },
  { iso2: "RS", name: "Serbia", dialCode: "381" },
  { iso2: "SC", name: "Seychelles", dialCode: "248" },
  { iso2: "SL", name: "Sierra Leona", dialCode: "232" },
  { iso2: "SG", name: "Singapur", dialCode: "65" },
  { iso2: "SY", name: "Siria", dialCode: "963" },
  { iso2: "SO", name: "Somalia", dialCode: "252" },
  { iso2: "LK", name: "Sri Lanka", dialCode: "94" },
  { iso2: "ZA", name: "Sudáfrica", dialCode: "27" },
  { iso2: "SD", name: "Sudán", dialCode: "249" },
  { iso2: "SS", name: "Sudán del Sur", dialCode: "211" },
  { iso2: "SE", name: "Suecia", dialCode: "46" },
  { iso2: "CH", name: "Suiza", dialCode: "41" },
  { iso2: "SR", name: "Surinam", dialCode: "597" },
  { iso2: "TH", name: "Tailandia", dialCode: "66" },
  { iso2: "TW", name: "Taiwán", dialCode: "886" },
  { iso2: "TZ", name: "Tanzania", dialCode: "255" },
  { iso2: "TJ", name: "Tayikistán", dialCode: "992" },
  { iso2: "TL", name: "Timor Oriental", dialCode: "670" },
  { iso2: "TG", name: "Togo", dialCode: "228" },
  { iso2: "TO", name: "Tonga", dialCode: "676" },
  { iso2: "TT", name: "Trinidad y Tobago", dialCode: "1868" },
  { iso2: "TN", name: "Túnez", dialCode: "216" },
  { iso2: "TM", name: "Turkmenistán", dialCode: "993" },
  { iso2: "TR", name: "Turquía", dialCode: "90" },
  { iso2: "TV", name: "Tuvalu", dialCode: "688" },
  { iso2: "UA", name: "Ucrania", dialCode: "380" },
  { iso2: "UG", name: "Uganda", dialCode: "256" },
  { iso2: "UY", name: "Uruguay", dialCode: "598" },
  { iso2: "UZ", name: "Uzbekistán", dialCode: "998" },
  { iso2: "VU", name: "Vanuatu", dialCode: "678" },
  { iso2: "VE", name: "Venezuela", dialCode: "58" },
  { iso2: "VN", name: "Vietnam", dialCode: "84" },
  { iso2: "YE", name: "Yemen", dialCode: "967" },
  { iso2: "DJ", name: "Yibuti", dialCode: "253" },
  { iso2: "ZM", name: "Zambia", dialCode: "260" },
  { iso2: "ZW", name: "Zimbabue", dialCode: "263" },
].sort((a, b) => a.name.localeCompare(b.name, "es"));

export const DEFAULT_COUNTRY_ISO2 = "CO";

export function countryFlagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(0x1f1e6 + char.charCodeAt(0) - 65));
}

// Splits a stored "573001234567" style number back into a country + local
// part by matching the longest known dial code prefix. Falls back to the
// default country with the full number as the local part.
export function splitPhoneNumber(digits: string): { country: Country; local: string } {
  const clean = digits.replace(/\D/g, "");
  const byLongestCode = [...COUNTRIES].sort((a, b) => b.dialCode.length - a.dialCode.length);
  for (const country of byLongestCode) {
    if (clean.startsWith(country.dialCode)) {
      return { country, local: clean.slice(country.dialCode.length) };
    }
  }
  const fallback = COUNTRIES.find((c) => c.iso2 === DEFAULT_COUNTRY_ISO2)!;
  return { country: fallback, local: clean };
}
